spring:
  application:
    name: pickup-pact-merchant-fulfillment
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/pickuppact}
    username: ${POSTGRES_USER:pickuppact}
    password: ${POSTGRES_PASSWORD:pickuppact}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: ${PORT:8082}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
