"""Semantic persistence port shared by the HTTP provider and outbox sender."""
from __future__ import annotations
from typing import Protocol


class PaymentStore(Protocol):
    def execute(self,command: dict,*,notification_copies: int=1,notification_delay: float=0) -> dict: ...
    def operation(self,operation_key: str) -> dict | None: ...
    def snapshot(self,world: str,order_id: str) -> dict: ...
    def consume_fault(self,world: str,operation_key: str,mode: str) -> bool: ...
    def storage_ready(self) -> bool: ...
    def claim_notifications(self,worker: str,*,limit: int=16,lease_seconds: int=30) -> list[dict]: ...
    def finish_notification(self,claim: dict,ok: bool) -> bool: ...
