spring:
  config:
    activate:
      on-profile: "redis,postgres,kafka"
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
pickup:
  capacity:
    default-units: ${PICKUP_SLOT_CAPACITY:40}
