'use strict';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const won=n=>Number(n).toLocaleString('ko-KR')+'원';
const time=n=>{const total=520+Number(n||0);return String(Math.floor(total/60)).padStart(2,'0')+':'+String(total%60).padStart(2,'0');};
const names={RESERVED:'제조 전',PREPARING:'제조 중',READY:'픽업 가능',PICKED_UP:'수령 완료',CANCELLED:'취소 완료'};
let state=null,catalog=null,drink='latte',activeView='customer',pendingPlan=null,busy=false,toastTimer;
function notify(message,error=false){clearTimeout(toastTimer);$('notice').textContent=message;$('notice').className=error?'error':'';$('notice').hidden=false;toastTimer=setTimeout(()=>$('notice').hidden=true,6500);}
async function api(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let data;try{data=await r.json();}catch(_){throw Error('서버 응답을 읽지 못했어요. 다시 시도해 주세요.');}if(!r.ok){const e=Error(typeof data.detail==='string'?data.detail:data.detail?.message||'입력 조건을 다시 확인해 주세요.');e.status=r.status;throw e;}return data;}
async function run(fn){if(busy)return;busy=true;document.body.classList.add('busy');try{await fn();}catch(e){notify(e.message,true);if(e.status===409&&state){try{state=await api('/api/route/journeys/'+state.id);render();}catch(_){}}}finally{busy=false;document.body.classList.remove('busy');}}
function requestId(){return (globalThis.crypto?.randomUUID?.()||Date.now()+'-'+Math.random().toString(36).slice(2)).replaceAll('-','');}
async function cmd(action,extra={}){state=await api('/api/route/journeys/'+state.id+'/commands',{action,expected_version:state.version,request_id:requestId(),...extra});render();return state;}
function labelIntent(intent){return (intent.drink==='latte'?'카페라떼':'아메리카노')+(intent.milk==='oat'?' · 오트':'')+(intent.decaf?' · 디카페인':'');}
function switchView(view){activeView=view;for(const v of ['customer','merchant','receipt'])$(v+'View').hidden=v!==view;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));renderAux();}
function adjustDeadline(){const n=Number($('deadline').value);$('deadlineValue').textContent=n;$('deadlineClock').textContent=time(n)+'까지';}
function pickDrink(value){drink=value;document.querySelectorAll('[data-drink]').forEach(b=>{const on=b.dataset.drink===value;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});$('oat').disabled=value==='americano';if(value==='americano')$('oat').checked=false;}
function fillIntent(i){$('destination').value=i.destination;$('deadline').value=i.deadline_minutes;$('budget').value=i.budget;$('detour').value=i.max_detour;$('priority').value=i.priority;pickDrink(i.drink);$('oat').checked=i.milk==='oat';$('decaf').checked=i.decaf;adjustDeadline();}
function cafeIcon(id){return `<div class="cafe-icon ${esc(id)}">${({wave:'W',corner:'C',oat:'O',garden:'G',express:'E'})[id]||'P'}</div>`;}
function selectedPlan(){return state?.current_plan||state?.recommendations?.[0]||null;}
function drawMap(plan=selectedPlan()){
 if(!catalog)return;
 const svg=$('map');const coords=id=>{const p=catalog.nodes[id];return [p[0]*9.3+25,p[1]*6.1+15];};
 const rects=[[105,145,100,130],[335,160,105,135],[435,355,155,90],[690,80,80,105],[740,300,130,94],[220,460,140,60],[820,450,90,90],[70,520,90,46],[415,68,150,74],[690,514,90,45]];
 let html=`<defs><pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".9" fill="#ced9c4"/></pattern><filter id="shadow"><feDropShadow dx="0" dy="5" stdDeviation="5" flood-color="#19432b" flood-opacity=".08"/></filter></defs><rect width="1000" height="660" fill="#f5f8f0"/><rect width="1000" height="660" fill="url(#grid)" opacity=".5"/><path d="M36 93Q95 28 211 85L234 167Q209 230 62 222Z" fill="#deebce"/><path d="M856 500Q968 407 998 445V648H889Z" fill="#e0ebd3"/>`;
 for(const [x,y,w,h] of rects)html+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="13" fill="#e9eee1" stroke="#e0e8d7"/>`;
 for(const [a,b] of catalog.edges){const x=coords(a),y=coords(b);html+=`<path d="M${x} L${y}" stroke="#e4eadd" stroke-width="26" stroke-linecap="round"/><path d="M${x} L${y}" stroke="#fff" stroke-width="21" stroke-linecap="round"/>`;}
 html+=`<text x="111" y="138" text-anchor="middle" fill="#92ad7b" font-size="15" class="map-text">CENTRAL PARK</text><text x="461" y="110" fill="#bbc8b0" font-size="13" letter-spacing="3" class="map-text">COFFEE DISTRICT</text><text x="390" y="406" fill="#b0bfa6" font-size="13" letter-spacing="3" class="map-text">MORNING AVENUE</text>`;
 if(plan){const path=plan.route.map((id,i)=>(i?'L':'M')+coords(id).join(',')).join(' ');const color=state?.risk.needs_attention&&state?.order?.store_id===plan.store_id?'#bb7751':'#287c58';html+=`<path d="${path}" fill="none" stroke="${color}" stroke-opacity=".12" stroke-width="25" stroke-linecap="round" stroke-linejoin="round"/><path d="${path}" fill="none" stroke="${color}" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><path d="${path}" fill="none" stroke="#ecf6e5" stroke-width="2" stroke-dasharray="2 16"/>`;}
 const all=state?.all_plans||[];
 for(const s of catalog.stores){const [x,y]=coords(s.id),p=all.find(p=>p.store_id===s.id),selected=plan?.store_id===s.id;let fill=selected?'#174b38':'#fff',textColor=selected?'#fff':'#4f6f4e';
  const label=p?(p.feasible?(time(p.arrival_at)+' 도착'):p.reason_labels[0]):s.name;
  html+=`<g transform="translate(${x},${y})" filter="url(#shadow)"><circle r="${selected?24:19}" fill="${fill}" stroke="${selected?'#174b38':'#c9d8bd'}" stroke-width="2"/><text y="6" text-anchor="middle" font-size="17" font-weight="800" fill="${textColor}" class="map-text">${({wave:'W',corner:'C',oat:'O',garden:'G',express:'E'})[s.id]}</text><rect x="-70" y="28" width="140" height="${p?47:30}" rx="9" fill="#ffffffed" stroke="${selected?'#b4cca2':'#e0e8d8'}"/><text y="47" text-anchor="middle" font-size="13" font-weight="700" fill="#234b37" class="map-text">${esc(s.name)}</text>${p?`<text y="65" text-anchor="middle" font-size="10" fill="${p.feasible?'#488252':'#a08571'}" class="map-text">${esc(label)}</text>`:''}</g>`;
 }
 for(const [id,label] of [['station','가상역 · 출발'],[state?.intent.destination||$('destination').value,'목적지']]){const [x,y]=coords(id);html+=`<g transform="translate(${x},${y})"><circle r="26" fill="${id==='station'?'#d7ec99':'#e9b48c'}"/><circle r="9" fill="#204d36"/><text y="-37" text-anchor="middle" font-size="15" font-weight="800" fill="#345438" class="map-text">${label}</text></g>`;}
 svg.innerHTML=html;
 $('mapTitle').textContent=plan?plan.name+'를 거쳐, '+time(plan.arrival_at)+' 도착':'한 잔을 위한, 더 좋은 길.';
 if(plan)$('mapSummary').innerHTML=`<div><span>커피 픽업</span><b>${time(plan.pickup_at)}</b></div><span class="summary-arrow">→</span><div><span>목적지 도착 예상</span><b>${time(plan.arrival_at)}</b></div><span class="summary-arrow">→</span><div><span>마감까지 ${plan.margin>=0?'여유':'지연'}</span><b>${Math.abs(plan.margin)}분 ${plan.margin>=0?'남아요':'늦어요'}</b></div>`;
}
function routeCard(p,index){const transfer=!!state.order;const diff=transfer?p.price-state.order.price:0;return `<article class="route-card ${index===0?'best':''}" data-hover="${esc(p.store_id)}">${cafeIcon(p.store_id)}<div class="route-copy"><h3>${esc(p.name)}${index===0?'<span class="tag">일정에 맞는 선택</span>':''}</h3><p>${esc(p.subtitle)}</p><div class="route-meta"><strong>${time(p.arrival_at)} 목적지 도착</strong><span>걷기 ${p.walk_total}분</span><span>매장 대기 ${p.wait}분</span></div></div><div class="route-right"><div class="route-price">${won(p.price)}${transfer?`<small> / 차액 ${diff>0?'+':''}${won(diff)}</small>`:''}</div><button class="primary" data-quote="${esc(p.quote_id)}">${transfer?'이 주문으로 옮기기':'이 경로로 주문'} <span>↗</span></button></div><div class="why">마감까지 ${p.margin}분 여유 · 직접 가는 길보다 ${p.detour}분 우회 · ${esc(labelIntent(state.intent))} 조건 유지</div></article>`;}
function renderRoutes(){if(!state)return;$('routeArea').hidden=false;const rows=state.recommendations;const active=state.order;
 if(active&&active.state!=='RESERVED'){$('routeArea').hidden=true;return;}
 let html=`<div class="route-heading"><div><h2>${active?'주문을 이어받을 수 있는 곳':'내 일정에 맞는 카페'}</h2><p>${active?'고객 동의 후 이동해요. 같은 주문 번호와 메뉴 조건은 그대로.':'제조 대기 + 픽업 + 목적지까지의 길을 함께 계산했어요.'}</p></div><span>${rows.length}곳 가능</span></div>`;
 if(rows.length)html+='<div class="route-list">'+rows.map(routeCard).join('')+'</div>';
 else html+=`<div class="empty-state"><span>↗</span><h2>지금 조건에 맞는 ${active?'다른 ':''}매장이 없어요.</h2><p>메뉴를 바꾸거나 예산을 넘겨서 주문하지 않아요.<br>${active?'현재 주문은 그대로 유지돼요. 제조 전이라면 취소할 수 있어요.':'도착 마감·예산·우회 조건을 조정하고 다시 찾아보세요.'}</p></div>`;
 const excluded=state.all_plans.filter(p=>!p.feasible);if(excluded.length)html+=`<details class="excluded"><summary>다른 ${excluded.length}곳을 추천하지 않은 이유</summary>${excluded.map(p=>`<div class="excluded-row"><b>${esc(p.name)}</b><span>${p.reason_labels.map(esc).join(' · ')}</span></div>`).join('')}</details>`;
 if(!active&&rows.length){const eligible=state.all_plans.filter(p=>!p.reasons.some(r=>['MENU','MILK','DECAF','OFFLINE'].includes(r)));const nearest=eligible.sort((a,b)=>a.walk_to-b.walk_to)[0];if(nearest&&nearest.store_id!==rows[0].store_id)html+=`<div class="comparison-note">거리만 보면 <b>${esc(nearest.name)}</b>, 도착 시간까지 보면 <b>${esc(rows[0].name)}</b>.<br>목적지 도착 예상 ${time(nearest.arrival_at)} → ${time(rows[0].arrival_at)}<small>동일 입력의 단순 거리순 선택과 비교한 계산입니다. 실제 패스오더의 추천 결과가 아닙니다.</small></div>`;}
 $('routeArea').innerHTML=html;
}
function orderActions(){const o=state.order;switch(o.state){case 'RESERVED':return `<div class="order-actions"><button class="primary" data-view="merchant">매장 화면에서 준비하기 <span>→</span></button><button class="secondary" data-action="cancel">주문 취소</button></div>`;case 'PREPARING':return `<div class="order-actions"><button class="primary" data-view="merchant">준비 상태 확인하기 <span>→</span></button></div>`;case 'READY':return `<div class="pickup"><p>매장에서 확인할 1회 수령 코드</p><strong id="pickupCode">${esc(o.pickup_code)}</strong><label for="claimCode" class="muted"><small>체험용으로 위 코드를 입력해 주세요.</small></label><div><input id="claimCode" inputmode="numeric" maxlength="6" placeholder="6자리 코드" aria-label="수령 코드"><button class="primary" id="claim">커피 받았어요</button></div></div>`;default:return `<div class="order-actions"><button class="primary" data-view="receipt">한 장의 영수증 보기 <span>↗</span></button></div>`;}}
function renderOrder(){const o=state?.order;$('orderArea').hidden=!o;if(!o)return;const p=state.current_plan,transfers=state.receipt.transfers;const title=o.state==='PICKED_UP'?'커피를 받았어요. 일정은 계속.':o.state==='CANCELLED'?'주문을 취소했어요.':o.state==='READY'?'당신의 한 잔이 준비됐어요.':transfers.length?'주문은 그대로, 더 나은 매장으로.':'오늘의 커피, 일정에 맞춰서.';
 let html=`<article class="order-card"><div class="order-top"><div><span class="eyebrow">MY ORDER / ${esc(o.id)}</span><h2>${title}</h2></div><span class="status-pill">${names[o.state]}</span></div><p class="order-subtitle"><b>${esc(o.store_name)}</b> · ${esc(labelIntent(state.intent))}</p><div class="order-stats"><div><span>목적지 도착 예상</span><b>${time(p.arrival_at)}</b></div><div><span>도착 마감</span><b>${time(state.intent.deadline_minutes)}</b></div><div><span>모의 주문 금액</span><b>${won(o.price)}</b></div></div>`;
 if(transfers.length){const t=transfers.at(-1);html+=`<div class="success-banner">✓ ${esc(t.data.from_name)}에서 ${esc(t.data.to_name)}로 이동했어요.<br>주문 번호는 ${esc(o.id)} 그대로 · 처음부터 재주문할 필요 없어요.</div>`;}
 if(state.risk.needs_attention){html+=`<div class="rescue-banner"><h3>${p.margin<0?'지금 매장에서는 '+Math.abs(p.margin)+'분 늦을 수 있어요.':'지금은 도착 조건을 지키기 어려워요.'}</h3><p>${state.risk.can_transfer?'아래에서 가능한 매장을 골라, 이 주문 그대로 옮기세요.':'이미 제조가 시작되어 주문을 옮기지 않아요. 중복 제조·결제를 만들지 않고 현재 상태를 알려드려요.'}</p></div>`;}
 html+=orderActions()+`<p class="order-reference">모의 승인 ${state.receipt.authorization_count}건 · 최종 모의 결제 ${state.receipt.capture_count}건 · 새로고침해도 같은 주문</p>`;
 if(!['CANCELLED','PICKED_UP'].includes(o.state))html+=`<details class="scenario-controls" open><summary>상황을 바꿔 직접 체험하기</summary><p>가상 환경만 바뀝니다. 결과와 경로는 서버가 다시 계산해요.</p><div class="order-actions"><button class="secondary" data-action="busy">현재 매장 12분 더 혼잡</button><button class="secondary" data-action="delay">출발 3분 늦어짐</button><button class="secondary" data-action="refresh">상태 새로 읽기</button></div></details>`;
 $('orderArea').innerHTML=html+'</article>';
}
function emptyView(title){return `<div class="empty-view"><h2>${title}</h2><p>내 이동에서 일정과 커피를 먼저 선택해 주세요.</p><button class="primary" data-view="customer">내 일정으로 돌아가기</button></div>`;}
function renderMerchant(){if(!state?.order){$('merchantContent').innerHTML=emptyView('아직 받은 주문이 없어요.');return;}const o=state.order,p=state.current_plan;
 const tiles=state.stores.map(s=>`<div class="merchant-tile ${s.id===o.store_id?'selected':''}">${cafeIcon(s.id)}<div><h3>${esc(s.name)}</h3><p>${s.id===o.store_id?(o.state==='CANCELLED'?'취소된 주문':names[o.state]):'이 주문의 제조 권한 없음'}</p></div></div>`).join('');
 let controls='';if(o.state==='RESERVED'){const advance=Math.max(0,p.start_at-state.clock);controls=(advance?`<button class="secondary" data-action="advance" data-minutes="${Math.min(30,advance)}">제조 시작 시각으로 ${Math.min(30,advance)}분 진행</button>`:'')+`<button class="primary" data-action="start" ${advance||state.risk.needs_attention?'disabled':''}>이 매장에서 제조 시작</button>`;}else if(o.state==='PREPARING'){const left=Math.max(0,o.ready_at-state.clock);controls=(left?`<button class="secondary" data-action="advance" data-minutes="${Math.min(30,left)}">제조 시간 ${Math.min(30,left)}분 진행</button>`:'')+`<button class="primary" data-action="ready" ${left?'disabled':''}>준비 완료 알리기</button>`;}else controls='<button class="primary" data-view="customer">고객 화면에서 확인하기</button>';
 $('merchantContent').innerHTML=`<div class="merchant-layout"><div class="merchant-stores">${tiles}</div><div class="merchant-ticket"><div class="ticket-number">동일 주문 ${esc(o.id)}</div><div class="order-top"><h2>${esc(o.store_name)}</h2><span class="status-pill">${names[o.state]}</span></div><div class="ticket-drink"><span class="mini-cup ${state.intent.drink==='latte'?'latte':'americano'}"></span><div><h3>${esc(labelIntent(state.intent))}</h3><p>1잔 · ${won(o.price)} · 메뉴 조건 변경 없음</p></div></div><div class="order-stats"><div><span>고객의 도착 마감</span><b>${time(state.intent.deadline_minutes)}</b></div><div><span>예상 준비 완료</span><b>${time(o.state==='RESERVED'?p.ready_at:o.ready_at)}</b></div><div><span>가상 현재 시각</span><b>${time(state.clock)}</b></div></div><p class="ticket-status">${o.state==='RESERVED'?'아직 제조 전이에요. 고객이 매장을 옮기면 이곳에서는 제조할 수 없어요.':o.state==='PREPARING'?'제조를 시작했어요. 이제 다른 매장으로 이관하거나 자동 취소할 수 없어요.':'고객 화면과 같은 주문 상태를 보고 있어요.'}</p>${state.risk.needs_attention?'<div class="rescue-banner"><h3>고객의 시간 조건에 변경이 필요해요.</h3><p>가능한 경우 고객 화면에서 다른 매장을 선택해 주세요.</p></div>':''}<div class="order-actions">${controls}</div><details class="scenario-controls"><summary>가상 시계 안내</summary><p>실제 기다리지 않고 제조 과정을 체험하도록 시계를 직접 진행합니다. 이동 GPS나 실물 제조 완료 신호는 수집하지 않습니다.</p></details></div></div>`;
}
function renderReceipt(){if(!state?.order){$('receiptContent').innerHTML=emptyView('첫 영수증을 기다리고 있어요.');return;}const o=state.order,r=state.receipt;
 const rows=[['현재 매장',o.store_name],['메뉴',labelIntent(state.intent)],['주문 상태',names[o.state]],['첫 매장',o.original_store],['매장 이동',r.transfers.length+'회'],['모의 승인',r.authorization_count+'건'],['최종 모의 결제',r.capture_count+'건']];
 const meaningful=state.events.filter(e=>!['CLOCK_ADVANCED'].includes(e.type));
 $('receiptContent').innerHTML=`<div class="receipt-layout"><article class="receipt-paper"><span class="eyebrow">PICKUP PACT / SIMULATED RECEIPT</span><h2>여러 선택, 한 장의 영수증.</h2><p class="receipt-id">${esc(o.id)}</p>${rows.map(([a,b])=>`<div class="receipt-row"><span>${a}</span><b>${esc(b)}</b></div>`).join('')}${r.transfers.map(t=>`<div class="receipt-row"><span>이동 시 차액 조정</span><b>${t.data.difference>0?'+':''}${won(t.data.difference)}</b></div>`).join('')}<div class="receipt-row total"><span>${r.capture_count?'최종 모의 결제':'모의 결제 예정'}</span><b>${won(r.capture_count?r.net_paid:r.payable)}</b></div><p>실제 결제 영수증이 아닙니다. 매장 이동은 주문을 추가하지 않으며, 모의 결제 확정은 수령 시 한 번만 기록합니다.</p><div class="order-actions"><a class="secondary" href="/api/route/journeys/${esc(state.id)}/receipt" target="_blank" rel="noopener">원본 기록 보기 ↗</a><button class="secondary" data-action="refresh">최신 상태 읽기</button></div></article><section class="panel timeline"><h2>내 한 잔이 이어진 과정</h2>${meaningful.map(e=>`<div class="event-row"><time>${time(e.at)}</time><div class="event-line"></div><div><b>${esc(e.title)}</b><small>${e.type==='ORDER_TRANSFERRED'?'주문 '+esc(e.data.order_id)+' 유지':e.type==='INTENT_CREATED'?'가상 환경 · 내 시간과 메뉴 조건':e.data.amount!==undefined?won(e.data.amount):'서버에 저장된 주문 기록'}</small></div></div>`).join('')}</section></div>`;
}
function renderAux(){renderMerchant();renderReceipt();if(state)document.dispatchEvent(new CustomEvent('route:aux-render',{detail:state}));}
function render(){if(!state)return;localStorage.setItem('pickup-pact.route-journey',state.id);$('clock').textContent=time(state.clock);$('startHint').hidden=true;document.body.classList.toggle('compact',!!state.order);$('intentForm').hidden=!!state.order;$('lockedIntent').hidden=!state.order;
 if(state.order){$('lockedIntent').innerHTML=`<h3 class="locked-title">${time(state.intent.deadline_minutes)}까지, ${state.intent.destination==='office'?'오피스 타워':'센트럴 파크'}.</h3><div class="locked-info"><span><b>${esc(labelIntent(state.intent))}</b></span><span>예산 <b>${won(state.intent.budget)}</b></span><span>허용 우회 <b>${state.intent.max_detour}분</b></span><span>출발 <b>가상역 2번 출구</b></span></div><p class="locked-statement">매장을 바꿔도<br><b>메뉴 조건 · 예산 · 주문 번호는 그대로.</b><br>차액과 이동 내역은 영수증에 남아요.</p>`;}
 $('stepLabel').textContent=state.order?(state.order.state==='PICKED_UP'?'04 / 한 주문으로 수령 완료':'03 / 내 주문을 끝까지 이어가기'):'02 / 내 일정에 맞는 경로';$('stepHint').textContent=state.order?'고객·매장·영수증이 같은 주문을 봅니다.':'추천 순서와 제외 이유를 직접 확인하세요.';renderOrder();renderRoutes();drawMap();renderAux();document.dispatchEvent(new CustomEvent('route:render',{detail:state}));}
function transferDialog(p){pendingPlan=p;const o=state.order,d=p.price-o.price;$('dialogBody').innerHTML=`<div class="dialog-box">${esc(o.store_name)}<br><b>↓ ${esc(p.name)}</b></div><div class="dialog-detail"><span>유지되는 주문 번호</span><b>${esc(o.id)}</b></div><div class="dialog-detail"><span>음료 조건</span><b>${esc(labelIntent(state.intent))}</b></div><div class="dialog-detail"><span>모의 주문 금액</span><b>${won(o.price)} → ${won(p.price)}</b></div><div class="dialog-detail"><span>차액</span><b>${d>0?'+':''}${won(d)}</b></div><div class="dialog-detail"><span>목적지 도착 예상</span><b>${time(p.arrival_at)} · ${p.margin}분 여유</b></div><p class="muted" style="font-size:10px;margin-top:14px">동의한 뒤에만 이동합니다. 승인 직전 매장 상태와 예산을 다시 확인해요.</p>`;document.dispatchEvent(new CustomEvent('route:transfer-preview',{detail:{state,plan:p}}));$('confirmDialog').showModal();}
$('intentForm').addEventListener('submit',e=>{e.preventDefault();run(async()=>{state=await api('/api/route/journeys',{destination:$('destination').value,deadline_minutes:Number($('deadline').value),drink,milk:$('oat').checked?'oat':'regular',decaf:$('decaf').checked,budget:Number($('budget').value),max_detour:Number($('detour').value),priority:$('priority').value,coupon_id:$('coupon').value||null,points:Number($('points').value)});render();notify(state.recommendations.length?'입력한 조건에 맞는 경로를 찾았어요.':'조건에 맞는 매장이 없어요. 조건을 조정해 주세요.',!state.recommendations.length);$('routeArea').scrollIntoView({behavior:'smooth',block:'nearest'});});});
$('deadline').addEventListener('input',adjustDeadline);$('destination').addEventListener('change',()=>{if(!state)drawMap();});
$('reset').addEventListener('click',()=>{localStorage.removeItem('pickup-pact.route-journey');location.href='/';});
$('dismissDialog').addEventListener('click',()=>$('confirmDialog').close());
$('confirmTransfer').addEventListener('click',()=>run(async()=>{const p=pendingPlan;$('confirmDialog').close();await cmd('transfer',{quote_id:p.quote_id});notify('주문 번호 그대로, '+p.name+'로 옮겼어요.');}));
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){switchView(b.dataset.view);window.scrollTo({top:0,behavior:'smooth'});return;}if(b.dataset.drink){pickDrink(b.dataset.drink);return;}if(b.dataset.quote){const p=state.recommendations.find(p=>p.quote_id===b.dataset.quote);if(!p)return;if(state.order){transferDialog(p);return;}run(async()=>{await cmd('reserve',{quote_id:p.quote_id});notify(p.name+'에 주문했어요. 혼잡해지면 다른 매장으로 옮길 수 있어요.');window.scrollTo({top:0,behavior:'smooth'});});return;}if(b.id==='claim'){run(async()=>{await cmd('claim',{pickup_code:$('claimCode').value.trim()});notify('수령 완료! 최종 모의 결제는 한 번만 기록했어요.');});return;}
 if(b.dataset.action){run(async()=>{switch(b.dataset.action){case 'busy':await cmd('disrupt',{store_id:state.order.store_id,minutes:12});notify('매장 혼잡을 반영했어요. 가능한 경로를 다시 계산했어요.');break;case 'delay':await cmd('delay',{minutes:3});notify('출발 지연을 반영했어요.');break;case 'advance':await cmd('advance',{minutes:Number(b.dataset.minutes)});break;case 'start':await cmd('start');notify('이 매장에서 제조를 시작했어요.');break;case 'ready':await cmd('ready');notify('커피가 준비됐어요. 고객 화면에서 수령 코드를 확인하세요.');break;case 'cancel':await cmd('cancel');notify('제조 전 주문을 취소하고 모의 승인을 해제했어요.');break;case 'refresh':state=await api('/api/route/journeys/'+state.id);render();notify('서버의 최신 주문을 읽었어요.');break;}});}
});
document.addEventListener('mouseover',e=>{const card=e.target.closest('[data-hover]');if(card&&!state?.order){const p=state.all_plans.find(p=>p.store_id===card.dataset.hover);if(p)drawMap(p);}});
(async()=>{try{catalog=await api('/api/route/catalog');drawMap();const saved=localStorage.getItem('pickup-pact.route-journey');if(saved){try{state=await api('/api/route/journeys/'+saved);fillIntent(state.intent);render();}catch(e){localStorage.removeItem('pickup-pact.route-journey');notify('이전 체험이 만료됐어요. 새 일정으로 시작해 주세요.');}}renderAux();}catch(e){notify('화면을 연결하지 못했어요. 새로고침해서 다시 시도해 주세요.',true);}})();
