apiVersion: v1
kind: Secret
metadata:
  name: pickup-pact-secrets
  namespace: pickup-pact
type: Opaque
stringData:
  POSTGRES_USER: replace-me
  POSTGRES_PASSWORD: replace-me
  POSTGRES_DSN: postgresql://replace-me:replace-me@postgres.example:5432/pickuppact
